# Contenido de las landings. Una intención de búsqueda por página:
# si dos pudieran rankear por lo mismo, van fusionadas.

LANDINGS = [
{
 "slug": "automatizacion-facturacion",
 "title": "Automatización de facturación con IA en Madrid | NitidFlow",
 "desc": "Automatizamos la facturación de tu empresa: emisión, cobros, remesas y conciliación. Preparados para Verifactu. Agencia en Madrid, auditoría gratuita.",
 "kw": "automatización de facturación",
 "h1": "Automatización de facturación con IA para empresas",
 "eyebrow": "AUTOMATIZACIÓN DE FACTURACIÓN",
 "lede": "Emitir, enviar, cobrar y conciliar facturas es de los procesos que más horas consume y menos criterio necesita. Es el primer sitio donde miramos.",
 "servicio": "Automatización de procesos de facturación",
 "secciones": [
  ("Qué se automatiza en un ciclo de facturación", [
   "En la mayoría de las pymes con las que trabajamos, una factura pasa por cuatro o cinco manos antes de cobrarse. Alguien recoge el albarán o el parte de trabajo, otra persona lo pasa al programa de facturación, una tercera revisa que los importes cuadren, y al final del mes alguien persigue los impagos por teléfono.",
   "Cada uno de esos pasos es automatizable sin cambiar de programa. Conectamos lo que ya usas —Holded, Sage, A3, Odoo, Factusol— con el resto de tus herramientas para que la factura se genere desde el dato de origen, se envíe sola y se concilie contra el banco cuando entra el pago.",
   "Lo que no automatizamos es la revisión. Una factura mal emitida cuesta más que el tiempo que ahorras, así que dejamos siempre un punto de control humano antes del envío. Es una decisión deliberada, no una limitación técnica.",
  ]),
  ("Facturación automatizada y lista para Verifactu", [
   "El reglamento Verifactu obliga a que los sistemas de facturación generen registros encadenados e inalterables, con su huella y su código QR. Para muchas empresas eso significa cambiar o actualizar el programa de facturación, y revisar los procesos que lo alimentan.",
   "Si vamos a tocar tu facturación, lo hacemos ya alineado con ese requisito. No añadimos capas que después haya que rehacer: trabajamos sobre software que cumple y dejamos documentado qué genera cada registro y desde dónde.",
   "Y una cosa que decimos siempre: el cumplimiento va por delante de la elegancia técnica. Si una automatización bonita complica tu trazabilidad fiscal, no la hacemos.",
  ]),
  ("Cuántas horas ahorra automatizar la facturación", [
   "Depende del volumen, pero el patrón se repite. Una empresa que emite entre 200 y 600 facturas al mes suele dedicar entre 20 y 40 horas mensuales al ciclo completo: emisión, envío, seguimiento de cobro y conciliación.",
   "Automatizado, ese trabajo baja a un par de horas de revisión. No es magia: es que el 90% de esas horas eran mover datos de un sitio a otro, y eso lo hace una máquina mejor que una persona.",
   "En la auditoría medimos tu caso concreto antes de proponerte nada. Si los números no salen, te lo decimos y no hacemos el proyecto.",
  ]),

  ("Cómo automatizamos tu facturación, paso a paso", [
   "Empezamos mirando facturas reales, no un diagrama. Pedimos el histórico de los últimos tres meses y seguimos el recorrido completo de una docena: de dónde sale el dato, quién lo toca, cuánto tarda en cobrarse y qué pasa cuando algo se tuerce.",
   "De ahí sale el mapa de dónde se van las horas, que casi nunca coincide con lo que la empresa cree. El cuello de botella suele estar en la revisión previa al envío o en el seguimiento del impago, no en la emisión.",
   "Después construimos por fases, empezando por el tramo que más horas devuelve. Quieres ver resultados en la primera semana, no en el mes cuatro, y así también validamos el enfoque antes de tocar el resto del ciclo.",
   "Al terminar te queda documentado qué hace cada flujo, dónde vive y cómo se para si algún día hace falta. Sin eso, una automatización es una caja negra que nadie se atreve a tocar.",
  ]), ],
 "faq_h2": "Preguntas sobre automatización de facturación",
 "faq": [
  ("¿Tengo que cambiar mi programa de facturación?",
   "Casi nunca. Trabajamos sobre Holded, Sage, A3, Odoo, Factusol y cualquier otro con API o exportación. Solo recomendamos cambiar si el que tienes no puede cumplir Verifactu, y en ese caso te lo decimos antes de empezar."),
  ("¿Esto me deja preparado para Verifactu?",
   "Diseñamos las automatizaciones para que los registros los genere un sistema que cumple. Nosotros no somos tu asesoría fiscal: coordinamos con quien lleve tu contabilidad para que la parte técnica y la fiscal encajen."),
  ("¿Dónde quedan mis datos?",
   "En tus cuentas. Todo lo que construimos vive en tu infraestructura y tus licencias, documentado. Si un día dejamos de trabajar juntos, los flujos siguen funcionando sin nosotros."),
  ("¿Cuánto tarda?",
   "Un ciclo de facturación completo suele estar funcionando en tres a cinco semanas, desplegado por fases para que no pares de facturar mientras tanto."),
 ],
},
{
 "slug": "automatizacion-whatsapp",
 "title": "Automatización de WhatsApp para empresas | NitidFlow Madrid",
 "desc": "Automatizamos la atención por WhatsApp de tu empresa con IA: respuestas, citas, avisos y conexión con tu CRM. Agencia en Madrid, auditoría gratuita.",
 "kw": "automatización de WhatsApp",
 "h1": "Automatización de WhatsApp con IA para empresas",
 "eyebrow": "AUTOMATIZACIÓN DE WHATSAPP",
 "lede": "En España el cliente escribe por WhatsApp, no por email. El problema no es recibir mensajes: es que se contesten a tiempo y no se pierda ninguno.",
 "servicio": "Automatización de atención al cliente por WhatsApp",
 "secciones": [
  ("Por qué automatizar WhatsApp en tu empresa", [
   "Cualquier negocio español con atención al cliente sabe que el grueso de las consultas llega por WhatsApp. Y sabe también lo que eso significa en la práctica: un móvil de empresa que solo mira una persona, conversaciones que se quedan sin responder el fin de semana, y ninguna forma de saber cuántas consultas se convirtieron en venta.",
   "Automatizar ese canal no es poner un bot que conteste tonterías. Es conectar WhatsApp Business con el resto de tu operación para que cada mensaje entre en un sistema, se clasifique y llegue a quien tiene que atenderlo, con el histórico del cliente delante.",
  ]),
  ("Qué hace la IA en tu WhatsApp y qué no", [
   "La IA se ocupa de lo repetitivo: entender qué pide el cliente, responder lo que ya está documentado —horarios, disponibilidad, estado de un pedido—, recoger los datos que hacen falta y agendar una cita en el calendario.",
   "Lo que no hacemos es dejar a la IA cerrando ventas o gestionando reclamaciones sola. En cuanto la conversación se sale de lo previsto, entra una persona con todo el contexto ya recogido. El cliente no repite nada y tu equipo no empieza de cero.",
   "Ese límite es intencionado. Un agente que improvisa delante de un cliente enfadado te cuesta más de lo que te ahorra.",
  ]),
  ("WhatsApp Business API conectado a tu CRM", [
   "Un WhatsApp automatizado que no habla con tu CRM sirve de poco. Cada conversación crea o actualiza la ficha del cliente, deja registrado lo que pidió y dispara lo que toque: un aviso al comercial, un presupuesto, un recordatorio de cita.",
   "Trabajamos sobre la API oficial de WhatsApp Business, no sobre soluciones que dependen de tener un móvil encendido. Eso importa: las alternativas no oficiales se caen sin avisar y pueden costarte el número.",
  ]),

  ("Sectores donde la automatización de WhatsApp rinde más", [
   "Clínicas y centros médicos: confirmación y recordatorio de citas, gestión de cambios y reducción de las ausencias sin llamar una por una.",
   "Comercio y ecommerce: estado del pedido, devoluciones y preguntas sobre disponibilidad, que son la mayoría del volumen y las más repetitivas.",
   "Servicios profesionales y talleres: recogida de datos antes de la primera cita, presupuestos y avisos de trabajo terminado.",
   "El patrón común es tener muchas consultas parecidas y poca gente para atenderlas. Cuando cada conversación es distinta y compleja, automatizar aporta menos y te lo diremos en la auditoría.",
  ]),
  ("Costes y consentimiento en WhatsApp Business", [
   "WhatsApp cobra por conversación iniciada por la empresa, con tarifas distintas según sea de servicio, de marketing o de utilidad. Ese coste hay que meterlo en el cálculo de retorno desde el principio, no descubrirlo en la primera factura.",
   "También hay que cuidar el consentimiento. Escribir a un cliente que no lo ha dado es un problema de RGPD y además la vía rápida a que te bloqueen el número por reportes de spam.",
   "Lo montamos con esos dos límites puestos desde el diseño, porque salen más caros de arreglar después que de respetar al principio.",
  ]), ],
 "faq_h2": "Preguntas sobre automatización de WhatsApp",
 "faq": [
  ("¿Necesito WhatsApp Business API?",
   "Sí, y te ayudamos a darla de alta. Es la única vía oficial y estable: las soluciones que simulan un móvil conectado acaban bloqueadas y puedes perder el número de empresa."),
  ("¿El cliente nota que habla con una máquina?",
   "Se lo decimos desde el primer mensaje. Ocultarlo genera desconfianza y, con la normativa europea de IA, también problemas. Funciona mejor ser claro y ofrecer paso a una persona en cualquier momento."),
  ("¿Se puede usar para avisos y no solo para atender?",
   "Sí: confirmaciones de cita, avisos de estado de pedido o recordatorios de pago. Con una condición, y es que el destinatario haya dado su consentimiento. Sin eso no lo hacemos."),
  ("¿Cómo se mide si funciona?",
   "Tiempo de primera respuesta, porcentaje de consultas resueltas sin intervención y conversaciones que acaban en cita o pedido. Lo dejamos en un cuadro de mando desde el primer día."),
 ],
},
{
 "slug": "automatizar-holded",
 "title": "Automatizar Holded en Madrid | NitidFlow",
 "desc": "Conectamos Holded con tus herramientas y automatizamos facturas, contactos y cobros. Agencia de automatización con IA en Madrid. Auditoría gratuita.",
 "kw": "automatizar Holded",
 "h1": "Automatizar Holded y conectarlo con tus herramientas",
 "eyebrow": "INTEGRACIONES CON HOLDED",
 "lede": "Holded resuelve bien la gestión, pero rara vez está solo. El trabajo manual aparece justo en los huecos: entre Holded y tu CRM, tu tienda o tu banco.",
 "servicio": "Integración y automatización de Holded",
 "secciones": [
  ("Dónde se pierde el tiempo con Holded", [
   "Holded hace su trabajo. El problema suele estar en lo que ocurre antes y después: alguien crea el contacto a mano porque el lead entró por la web, alguien copia el pedido de la tienda online para emitir la factura, alguien revisa a final de mes qué está cobrado cruzando el extracto del banco con el listado de facturas.",
   "Ese trabajo no lo arregla ninguna función de Holded, porque no vive dentro de Holded. Vive en los huecos entre Holded y todo lo demás. Y es exactamente donde se automatiza mejor.",
  ]),
  ("Integraciones con Holded más habituales", [
   "De la web al contacto: un formulario o un lead de campaña crea el contacto en Holded con sus datos y su origen, sin que nadie teclee nada.",
   "De la tienda a la factura: cada pedido de PrestaShop, WooCommerce o Shopify genera su factura en Holded, con los impuestos y la serie correctos.",
   "Del banco a la conciliación: los cobros se cruzan solos y lo que queda pendiente dispara un aviso de seguimiento en vez de una revisión manual.",
   "Del CRM a presupuestos: una oportunidad ganada genera el presupuesto o la factura sin salir del flujo comercial.",
  ]),
  ("Cómo automatizamos Holded con su API y n8n", [
   "Usamos la API de Holded y n8n como capa de orquestación, alojado en tu infraestructura. No metemos intermediarios que se queden tus datos ni plataformas que te cobren por cada ejecución cuando crezcas.",
   "Una regla que no nos saltamos: el dato tiene una sola fuente de verdad. Si el cliente vive en Holded, el CRM lo consulta pero no lo duplica. Los espejos sincronizados en dos direcciones acaban siempre en registros contradictorios y en alguien decidiendo a mano cuál es el bueno.",
   "Todo queda documentado y en tus cuentas. Si mañana te llevas el proyecto a otro equipo, funciona igual.",
  ]),

  ("Ejemplo: de formulario web a factura en Holded", [
   "Un cliente rellena el formulario de presupuesto en la web. En lugar de acabar en un correo que alguien tiene que leer, el dato entra en el flujo: se crea el contacto en Holded si no existía, se genera el presupuesto con la plantilla y los precios que correspondan, y se avisa al comercial en Slack o por WhatsApp con el enlace ya listo para enviar.",
   "Si el cliente acepta, el presupuesto pasa a factura sin volver a teclear nada. Cuando el cobro entra, la conciliación lo cruza y cierra el ciclo. Si a los diez días no ha entrado, sale un recordatorio automático y, si sigue sin pagarse, un aviso al responsable.",
   "Ninguno de esos pasos es complicado por separado. Lo que cuesta es que ocurran solos, en orden y sin que nadie tenga que acordarse. Ahí es donde está el ahorro.",
  ]),
  ("Qué necesitamos para automatizar tu Holded", [
   "Acceso a la API de Holded, saber qué otras herramientas están en juego y una hora de alguien que conozca cómo se hace hoy el trabajo de verdad. Con eso solemos tener suficiente para decirte qué se puede automatizar y qué retorno tiene.",
   "No hace falta que tengas nada preparado ni que hayas ordenado los procesos antes. Verlos como están es justamente lo útil: lo que se ha ido improvisando con los años es donde suele estar el mayor ahorro escondido.",
  ]), ],
 "faq_h2": "Preguntas sobre automatizar Holded",
 "faq": [
  ("¿Hace falta un plan concreto de Holded?",
   "Necesitas acceso a la API, disponible en los planes de pago. En la auditoría comprobamos qué permite tu plan actual antes de proponerte nada."),
  ("¿Funciona con otros programas además de Holded?",
   "Sí. Hacemos lo mismo con Sage, A3, Odoo y Factusol. El enfoque es idéntico: automatizar los huecos entre programas, no sustituir el que ya usas."),
  ("¿Y si cambio de herramienta más adelante?",
   "Como la lógica vive en una capa aparte y no dentro de Holded, se reconecta a otro sistema sin rehacer el proyecto entero."),
  ("¿Podéis dejar los datos solo en España?",
   "Sí. Podemos alojar la orquestación en servidores europeos o en tu propia máquina, según lo que exija tu política de datos."),
 ],
},
{
 "slug": "agentes-ia",
 "title": "Agentes de IA para empresas | NitidFlow Madrid",
 "desc": "Diseñamos agentes de IA que consultan tus sistemas, deciden y ejecutan acciones reales. Agencia en Madrid, auditoría gratuita.",
 "kw": "Agentes de IA",
 "h1": "Agentes de IA para empresas",
 "eyebrow": "AGENTES DE IA",
 "lede": "Agentes que entienden información, toman decisiones y ejecutan acciones. La diferencia con un chatbot no es la conversación: es que al final del proceso ha cambiado algo en tus sistemas.",
 "servicio": "Diseño e implementación de agentes de IA",
 "secciones": [
  ("Un chatbot responde. Un agente termina el trabajo.", [
   "La mayoría de proyectos de «IA en la empresa» acaban en un chat que contesta preguntas. Funciona una temporada y luego se abandona, porque responder no era el problema: el problema era que después de responder alguien tenía que abrir el CRM, crear el contacto, apuntar lo hablado y agendar la llamada.",
   "Un agente se diseña al revés. Parte de la acción que hay que ejecutar y de las herramientas donde ejecutarla, y la conversación es solo la entrada. Puede consultar información real en tus sistemas, decidir entre varias salidas posibles y dejar registro de lo que ha hecho.",
   "Eso también significa que un agente se equivoca de otra manera: no da una respuesta pobre, ejecuta una acción incorrecta. Por eso lo que importa al diseñarlo son los límites, no la autonomía.",
  ]),
  ("Señales de que te hace falta", [
   "Ya tenéis un chatbot y nadie lo usa",
   "Alguien transcribe a mano lo que se habla con el cliente",
   "Las consultas exigen mirar en dos o tres sistemas distintos",
   "El seguimiento depende de que alguien se acuerde",
   "Hay reglas que cambian según el caso y no caben en un formulario",
   "El equipo pasa más tiempo registrando que atendiendo",
  ]),
  ("Tres agentes que cubren la mayoría de casos.", [
   "No hacen falta veinte agentes. Casi todo el trabajo repetitivo de una pyme cae en uno de estos tres perfiles.",
   "<strong>Agente de ventas</strong> Recibe el lead, lo interpreta, lo cualifica con tus criterios, actualiza el CRM y arranca el seguimiento.",
   "<strong>Agente de atención</strong> Atiende la conversación, consulta el estado real del pedido o del expediente y escala cuando el caso lo pide.",
   "<strong>Agente de operaciones</strong> Convierte documentos y correos en datos estructurados, los valida y los escribe donde corresponde.",
   "<strong>Agente de cualificación</strong> Ordena una entrada masiva de solicitudes según prioridad real, no según orden de llegada.",
   "<strong>Agente de seguimiento</strong> Retoma conversaciones paradas con el contexto de lo que ya se habló, sin repetir el mismo mensaje.",
   "<strong>Agente de reporting</strong> Recoge datos de varios sistemas y redacta el informe recurrente con el mismo criterio cada vez.",
  ]),
  ("Cómo se construye un agente que no se descontrola.", [
   "Un agente útil no es el que puede hacer de todo, sino el que tiene un objetivo estrecho, herramientas concretas y un límite claro de dónde para.",
   "<strong>Un objetivo, no una personalidad</strong> El agente existe para cerrar un proceso concreto. Cuanto más estrecho el objetivo, más fiable el resultado.",
   "<strong>Herramientas explícitas</strong> Solo puede hacer lo que le hemos dado: consultar el CRM, crear un contacto, agendar. Nada más.",
   "<strong>Un punto de parada</strong> Casos fuera de guion, importes altos o clientes sensibles se derivan a una persona por diseño, no por excepción.",
   "<strong>Registro de cada paso</strong> Qué consultó, qué decidió y qué ejecutó. Sin traza no se puede depurar ni defender una decisión.",
  ]),
  ("Qué gana el equipo.", [
   "<strong>El registro deja de ser trabajo</strong> Lo que se habla queda apuntado sin que nadie lo transcriba después, que es cuando se pierde.",
   "<strong>Las consultas se resuelven con datos reales</strong> El agente mira el sistema antes de contestar, en lugar de improvisar sobre un texto genérico.",
   "<strong>El caso difícil llega antes a una persona</strong> Bien diseñado, un agente no intenta resolver lo que no puede: lo detecta y lo pasa con contexto.",
   "<strong>El criterio queda escrito</strong> Cualificar un lead deja de depender de quién lo lea. Las reglas están en un sitio y se pueden discutir.",
  ]),
  ("Qué no le pedimos a un agente", [
   "Negociar precios o condiciones comerciales",
   "Tomar decisiones con consecuencia legal o económica sin validación",
   "Sustituir la conversación cuando el cliente está enfadado",
   "Operar sobre sistemas sin API mediante automatización del navegador",
   "Inventar información que no está en vuestros datos",
  ]),
 ],
 "faq_h2": "Preguntas sobre agentes de ia",
 "faq": [
  ("¿Qué diferencia real hay entre un chatbot y un agente de IA?",
   "El alcance de lo que puede hacer. Un chatbot produce texto. Un agente tiene herramientas conectadas y puede consultar, crear y modificar registros en tus sistemas. La consecuencia práctica es que un chatbot mal hecho da una respuesta mala, y un agente mal hecho ejecuta una acción mala: por eso el diseño de límites importa más que el modelo."),
  ("¿Cuánta autonomía se le da?",
   "La mínima que resuelva el caso. Lo habitual es que las lecturas y consultas sean libres, las escrituras estén acotadas a operaciones concretas, y las acciones sensibles — enviar una propuesta, emitir una factura, cerrar una incidencia — requieran validación o cumplan una regla explícita."),
  ("¿Se puede saber por qué el agente hizo algo?",
   "Sí, si se ha construido para eso. Cada ejecución debe registrar la entrada, las consultas hechas, la decisión tomada y la acción ejecutada. Sin ese registro no hay forma de depurar un fallo ni de explicar una decisión a un cliente."),
  ("¿Qué modelo de IA usáis?",
   "Depende de la tarea, y no es una decisión definitiva. Interpretar un email corto y razonar sobre un expediente complejo no piden lo mismo. El sistema se construye para poder cambiar de modelo sin rehacer el flujo, porque en este terreno lo que hoy es la mejor opción en seis meses puede no serlo."),
  ("¿El agente aprende de nuestros datos?",
   "Consulta vuestros datos en el momento de responder, que es distinto de entrenar un modelo con ellos. Lo primero es lo que hace falta casi siempre y es reversible; lo segundo rara vez se justifica en una pyme y trae consigo un problema de privacidad y de mantenimiento."),
  ("¿Cuánto tarda en estar en producción?",
   "Un agente con un objetivo estrecho y sistemas con API suele medirse en semanas. Lo que alarga los plazos casi nunca es la IA: son los accesos, los permisos y descubrir que el proceso real no era el que estaba documentado."),
 ],
},
{
 "slug": "automatizacion-clinicas",
 "title": "Automatización con IA para clínicas | NitidFlow Madrid",
 "desc": "Automatizamos citas, recordatorios y documentación de tu clínica para reducir plantones y trabajo administrativo. Auditoría gratuita en Madrid.",
 "kw": "Clínicas",
 "h1": "IA para clínicas",
 "eyebrow": "CLÍNICAS",
 "lede": "La mayor parte del trabajo administrativo de una clínica son citas y recordatorios. Y la mayor parte de la pérdida son huecos que nadie ocupó.",
 "servicio": "Automatización de procesos para clínicas y consultas",
 "secciones": [
  ("Un hueco vacío no se recupera.", [
   "Una clínica vende tiempo. Cuando un paciente no aparece a su cita y nadie ocupa ese hueco, esa facturación no vuelve: no es un aplazamiento, es una pérdida. Y la causa más frecuente del plantón no es el desinterés, es el olvido.",
   "El segundo consumo de tiempo está en la recepción. Pedir cita, cambiarla, preguntar qué documentación traer, confirmar el horario. Todo por teléfono, en horario de clínica, con la persona de recepción interrumpiendo lo que estaba haciendo.",
   "Y hay un tercer punto específico de este sector: los datos que se manejan son datos de salud. Eso cambia el diseño de cualquier automatización, y no como un trámite añadido al final.",
  ]),
  ("Señales de que te hace falta", [
   "Hay un porcentaje conocido de citas a las que no acude nadie",
   "Recepción pasa la mañana al teléfono cambiando citas",
   "Fuera de horario no se puede pedir ni cambiar cita",
   "Los recordatorios se mandan a mano, o no se mandan",
   "Los huecos que se liberan a última hora quedan vacíos",
   "La documentación previa a la primera consulta llega incompleta",
  ]),
  ("Qué se automatiza en una clínica.", [
   "Lo administrativo, que es donde está el volumen. Empezando casi siempre por los recordatorios.",
   "<strong>Recordatorios con confirmación</strong> La automatización con mejor retorno del sector: cada plantón evitado es un hueco facturado.",
   "<strong>Petición y cambio de cita</strong> Sin llamar y fuera de horario, contra la agenda real y con las reglas de aviso que tengáis.",
   "<strong>Gestión de lista de espera</strong> Los huecos liberados a última hora se ofrecen automáticamente en lugar de quedar vacíos.",
   "<strong>Documentación previa</strong> Recogida de lo que hace falta antes de la primera consulta, para no perder tiempo en la sala.",
   "<strong>Preguntas frecuentes de recepción</strong> Horarios, dirección, precios de consulta, qué traer, cómo llegar. Resueltas sin interrumpir a nadie.",
   "<strong>Seguimiento post-consulta</strong> Recordatorio de revisión o de siguiente sesión según la pauta que defináis.",
  ]),
  ("Cómo se automatiza una clínica sin tocar lo clínico.", [
   "Todo lo que se automatiza es administrativo. Nada de lo que se automatiza toca criterio sanitario ni contenido de historia clínica.",
   "<strong>Cita por el canal del paciente</strong> Pedir, cambiar y confirmar por WhatsApp o web, a cualquier hora, contra la agenda real.",
   "<strong>Recordatorio con confirmación</strong> Aviso previo con opción de confirmar o reprogramar en un toque. Es la medida que más plantones evita.",
   "<strong>Lista de espera activa</strong> Cuando un hueco se libera, se ofrece automáticamente a quien estaba esperando.",
   "<strong>Datos de salud fuera del flujo</strong> La automatización gestiona la cita, no el contenido clínico. Ese dato se queda en vuestro sistema sanitario.",
  ]),
  ("Qué cambia.", [
   "<strong>Menos huecos vacíos</strong> Recordatorio con confirmación más lista de espera activa. Es la combinación que más recupera.",
   "<strong>Recepción deja de estar al teléfono</strong> Y puede atender bien al paciente que está delante, que es lo que se nota en la percepción de la clínica.",
   "<strong>El paciente puede gestionar fuera de horario</strong> Mucha gente solo puede llamar en horario laboral, que es justo cuando no puede llamar.",
   "<strong>La primera consulta empieza con todo listo</strong> Sin gastar los primeros diez minutos en papeles que se podían haber recogido antes.",
  ]),
  ("Lo que no se automatiza en una clínica", [
   "Ningún criterio clínico: triaje, diagnóstico, pauta o indicación",
   "Contenido de la historia clínica: la automatización no lo procesa",
   "Resultados de pruebas: los comunica un profesional, no un flujo",
   "Urgencias: cualquier indicio de urgencia se deriva a una persona de inmediato",
   "Consentimientos informados: se recogen, no se dan por supuestos",
  ]),
 ],
 "faq_h2": "Preguntas sobre clínicas",
 "faq": [
  ("¿Se pueden tratar datos de salud en una automatización?",
   "Los datos de salud son categoría especial en el RGPD y exigen una base jurídica reforzada, medidas de seguridad específicas y evaluación de impacto en muchos casos. Por eso el planteamiento por defecto es no meterlos en el flujo: la automatización gestiona la cita y el canal —nombre, teléfono, hora, profesional— y el contenido clínico se queda en vuestro software sanitario. Lo que salga de ese perímetro se decide con vuestro responsable de protección de datos, no por comodidad técnica."),
  ("¿Puede el sistema decidir la urgencia de un paciente?",
   "No, y no es una limitación técnica sino una línea que no cruzamos. El triaje es criterio sanitario. Lo que sí hace el flujo es detectar palabras o situaciones que sugieren urgencia y derivar inmediatamente a una persona, sin intentar resolverlo."),
  ("¿Cuánto se reducen los plantones?",
   "No lo sabemos sin vuestros datos, y cualquier porcentaje que os diéramos sería inventado. Lo que sí se puede hacer es medir vuestra tasa actual antes de empezar y compararla después: es una de las pocas automatizaciones donde el efecto es limpio de medir."),
  ("¿Funciona con nuestro software de gestión de clínica?",
   "Depende. El software sanitario suele ser cerrado y no siempre expone API. Cuando la hay, la integración es directa; cuando no, hay que valorar si se puede trabajar contra su agenda de otra forma o si conviene mantener la agenda automatizada sincronizada en un solo sentido. Se comprueba antes de comprometer nada."),
  ("¿Los pacientes mayores usan WhatsApp para esto?",
   "Más de lo que se suele suponer, pero no todos, y por eso el teléfono no debe desaparecer. Lo razonable es que el canal automatizado absorba a quien lo prefiera y libere la línea telefónica para quien la necesita. Sustituir el teléfono por completo en este sector es un error."),
 ],
},

{
 "slug": "verifactu",
 "title": "Verifactu: cómo adaptar tu facturación | NitidFlow Madrid",
 "desc": "Qué exige Verifactu, a quién afecta y cómo adaptar tu facturación sin rehacerla entera. Agencia de automatización en Madrid. Auditoría gratuita.",
 "kw": "Verifactu",
 "h1": "Verifactu: cómo adaptar la facturación de tu empresa",
 "eyebrow": "VERIFACTU",
 "lede": "Verifactu no es un programa que se instala: es una forma de emitir facturas. Lo que hay que revisar no es solo el software, sino los procesos que lo alimentan.",
 "servicio": "Adaptación de procesos de facturación a Verifactu",
 "secciones": [
  ("Qué exige Verifactu exactamente", [
   "El reglamento obliga a que los sistemas de facturación generen, por cada factura, un registro inalterable encadenado con el anterior. Cada registro lleva su huella, la de la factura previa y un código QR que permite verificarla. La cadena es la clave: si un registro se altera o desaparece, la cadena se rompe y queda constancia.",
   "En la práctica eso significa que ya no puedes emitir una factura, darte cuenta de un error y sobrescribirla. Hay que rectificar, y la rectificación deja su propio rastro. Muchos de los flujos improvisados que funcionaban en Excel dejan de ser viables.",
   "El otro cambio es de responsabilidad. El software debe declarar que cumple, pero quien responde de que sus facturas cumplan sigue siendo la empresa. Un programa conforme alimentado con un proceso desordenado no te protege.",
  ]),
  ("A quién afecta Verifactu y desde cuándo", [
   "Afecta a empresas y autónomos que emiten factura y no están en el Suministro Inmediato de Información. Es decir, a la mayoría de pymes españolas: las que están en SII ya cumplen por otra vía.",
   "Los plazos han cambiado más de una vez y conviene confirmarlos con tu asesoría antes de tomar decisiones. Lo que no cambia es la dirección: la factura verificable deja de ser opcional.",
   "Nuestra recomendación no es correr, es no llegar con prisas. Las adaptaciones hechas la última semana son las que acaban en procesos manuales que nadie documenta.",
  ]),
  ("Verifactu no es solo software: es proceso", [
   "Casi todas las empresas con las que hablamos hacen la misma pregunta: qué programa comprar. Y casi siempre esa es la parte fácil, porque los fabricantes españoles ya han adaptado sus productos.",
   "Lo difícil es lo que ocurre antes de la factura. Si el dato llega desde un albarán en papel, un pedido de la tienda online y una hoja de cálculo que alguien mantiene a mano, el programa conforme recibirá datos incorrectos y emitirá registros correctos de facturas equivocadas.",
   "Ahí es donde entramos. Ordenamos el camino del dato hasta la factura para que lo que se emite salga bien a la primera, con un punto de revisión humana antes del envío. Automatizar la emisión sin ordenar el origen solo acelera el error.",
  ]),
  ("Cómo adaptamos tu facturación a Verifactu", [
   "Primero miramos qué emites hoy y desde dónde. Facturas reales, no un diagrama: de dónde sale cada importe, quién lo toca y en qué punto se puede colar un fallo.",
   "Después vemos si tu software actual puede cumplir. Si puede, trabajamos sobre él. Si no puede, te lo decimos claro y coordinamos el cambio con tu asesoría, que es quien conoce tu situación fiscal.",
   "Y por último automatizamos el camino hasta la factura: que el dato llegue solo desde su origen, que la revisión sea rápida y que la rectificación, cuando toque, siga el procedimiento en lugar de improvisarse.",
   "No somos asesoría fiscal y no lo pretendemos. Trabajamos con la tuya: nosotros ponemos la parte técnica y ellos validan la fiscal.",
  ]),
 ],
 "faq_h2": "Preguntas frecuentes sobre Verifactu",
 "faq": [
  ("¿Verifactu me obliga a cambiar de programa de facturación?",
   "Solo si el que usas no va a adaptarse. Holded, Sage, A3, Odoo y los demás fabricantes españoles han adaptado sus productos. En la auditoría comprobamos tu versión concreta antes de recomendarte ningún cambio."),
  ("¿Sois una asesoría fiscal?",
   "No, y es importante. Nosotros nos ocupamos de los procesos y de la parte técnica. La interpretación fiscal la valida tu asesoría, y trabajamos coordinados con ella."),
  ("Facturo poco, ¿me afecta igual?",
   "El volumen no exime. Si emites factura y no estás en SII, te aplica. Lo que cambia con el volumen es el esfuerzo de adaptación, no la obligación."),
  ("¿Puedo seguir facturando con Excel?",
   "No como sistema de emisión. Excel puede seguir siendo una herramienta interna de cálculo, pero la factura tiene que emitirla un sistema que genere los registros encadenados."),
  ("¿Cuánto se tarda en adaptar la facturación?",
   "Si el software ya cumple, ordenar los procesos alrededor suele llevar de tres a cinco semanas. Si hay que migrar de programa, depende del histórico y de tu asesoría."),
 ],
},
{
 "slug": "automatizar-sage",
 "title": "Automatizar Sage: integraciones a medida | NitidFlow Madrid",
 "desc": "Conectamos Sage con tu CRM, tu tienda y tu banco, y automatizamos facturas y conciliación. Agencia de automatización con IA en Madrid.",
 "kw": "automatizar Sage",
 "h1": "Automatizar Sage y conectarlo con tus herramientas",
 "eyebrow": "INTEGRACIONES CON SAGE",
 "lede": "Sage lleva décadas siendo el estándar de la pyme española. El trabajo manual no está dentro: está en todo lo que entra y sale de él.",
 "servicio": "Integración y automatización de Sage",
 "secciones": [
  ("Dónde aparece el trabajo manual con Sage", [
   "Sage 50, Sage 200 o Sage Despachos hacen bien lo suyo. El problema es que casi nunca son el único sitio donde vive la información: el pedido entra por la tienda, el cliente nace en el CRM, el cobro llega al banco, y alguien tiene que unir los tres extremos a mano.",
   "Ese trabajo se reconoce fácil. Si alguien de tu equipo exporta un fichero de Sage cada semana, o teclea en Sage algo que ya existe en otro programa, ahí hay un proceso automatizable.",
   "Y suele ser mucho más tiempo del que parece, porque no se mide: son quince minutos aquí y media hora allá, repartidos entre varias personas.",
  ]),
  ("Integraciones con Sage que montamos más a menudo", [
   "<strong>Del CRM a Sage.</strong> El cliente que se gana en el CRM se crea en Sage con sus datos fiscales, sin duplicados ni tecleo.",
   "<strong>De la tienda a la factura.</strong> Los pedidos de PrestaShop, WooCommerce o Shopify entran como facturas con su serie e impuestos correctos.",
   "<strong>Del banco a la conciliación.</strong> Los movimientos se cruzan contra las facturas abiertas y lo que queda pendiente dispara el aviso de cobro.",
   "<strong>De Sage a los informes.</strong> Los datos salen a un cuadro de mando en vivo en lugar de a un Excel que alguien monta cada lunes.",
  ]),
  ("Cómo se conecta Sage por dentro", [
   "Sage no es una sola cosa: hay versiones de escritorio, versiones en la nube y despliegues sobre servidor propio, y no todas ofrecen la misma vía de conexión. Algunas tienen API, otras se integran contra su base de datos y otras vía importación y exportación programada.",
   "En la auditoría identificamos qué versión tienes y cuál es la vía viable. Es la primera pregunta que hay que responder, porque condiciona todo lo demás.",
   "Sobre eso montamos la orquestación en n8n alojado en tu infraestructura. Ni intermediarios que se queden tus datos, ni plataformas que te cobren por ejecución cuando el volumen crezca.",
   "Y mantenemos una regla: el dato tiene una sola fuente de verdad. Si el cliente vive en Sage, el CRM lo consulta pero no lo duplica. Los espejos que sincronizan en dos direcciones acaban en registros contradictorios y en alguien decidiendo a mano cuál vale.",
  ]),

  ("Qué cambia en el día a día al automatizar Sage", [
   "<strong>Se acaban las exportaciones semanales.</strong> Nadie vuelve a sacar un fichero de Sage para pegarlo en otro sitio: el dato viaja solo y llega donde tiene que llegar.",
   "<strong>Los duplicados desaparecen.</strong> Cuando el cliente se crea una sola vez y desde un solo origen, dejan de aparecer tres fichas del mismo con datos distintos.",
   "<strong>El cierre de mes deja de ser un sprint.</strong> Si la conciliación va corriendo a diario, a final de mes no queda una montaña que revisar contrarreloj.",
   "<strong>La información está cuando se necesita.</strong> Un cuadro de mando en vivo evita la pregunta de «¿cómo vamos?» seguida de dos días de recopilar números.",
  ]),
  ("Qué necesitamos para automatizar tu Sage", [
   "Saber qué versión de Sage tienes y cómo está desplegada, qué otras herramientas están en juego, y una hora de alguien que conozca cómo se hace hoy el trabajo de verdad.",
   "No hace falta que ordenes nada antes. Ver los procesos tal como están, con sus atajos y sus apaños de años, es justamente lo útil: ahí suele estar escondido el mayor ahorro.",
   "De esa sesión sale una lista priorizada de lo que se puede automatizar, con el tiempo que devuelve cada cosa. Te la llevas trabajes con nosotros o no.",
  ]), ],
 "faq_h2": "Preguntas sobre automatizar Sage",
 "faq": [
  ("¿Funciona con mi versión de Sage?",
   "Depende de cuál sea. Sage 200 y las versiones en la nube ofrecen vías de conexión más directas; en las de escritorio trabajamos contra la base de datos o con importaciones programadas. Lo comprobamos antes de proponer nada."),
  ("¿Tengo que migrar a la nube?",
   "No. Preferimos trabajar sobre lo que ya tienes. Si tu versión limita mucho lo que se puede automatizar te lo diremos, pero la decisión de migrar es tuya y no la forzamos."),
  ("¿Esto interfiere con mi asesoría?",
   "Al contrario: lo normal es que les facilite el trabajo, porque los datos llegan ordenados y a tiempo. Cuando hace falta, hablamos directamente con ellos."),
  ("¿Y si un día cambio de Sage a otro ERP?",
   "Como la lógica vive en una capa aparte y no dentro de Sage, se reconecta al nuevo sistema sin rehacer el proyecto entero."),
 ],
},
]
